### PR TITLE
removed parallax and page loader

### PR DESCRIPTION
**Pull request by marcmerce**
Pretty simple, I only deleted a shit ton of code!

### CODE REVIEW

**Comment by EFF** [comment]
@marcmercier1 why did you remove the parallax and loader ? you just didn't like them ?

**Comment by marcmerce** [comment]
@EFF Well, we've talked about this. We are going to remove the parallax and page loader because they are useless and because we will make the layout wider. You will see the next PR with new footer and wider layout

**Comment by marcmercier1** [comment]
screen shot 2017-03-04 at 12 36 39 pm

**Comment by marcmercier1** [comment]
Newsletter will become a pop-up to get more emails, the sitemap will have more item thus a wider layout is necessary. Same thing for the features section, a wider layout will look better with pictures on one side and text on the other

**Review by osylvain — APPROVED** [review]
lol I like that!

**Pull request merged**
